<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<ApplicationIcon>appIcon.ico</ApplicationIcon>
		<AssemblyTitle>RestXMLTranslator</AssemblyTitle>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<Version>2.13</Version>
		<AssemblyVersion>$(Version)</AssemblyVersion>
		<FileVersion>$(Version)</FileVersion>
		<InformationalVersion>13</InformationalVersion>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
		<SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="appIcon.ico" />
		<None Remove="locale_en.json" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="appIcon.ico" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="locale_en.json">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</EmbeddedResource>
		<EmbeddedResource Include="locale_ru.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</EmbeddedResource>
	</ItemGroup>

</Project>
